CREATE TABLE events
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    start_date  TIMESTAMP WITHOUT TIME ZONE,
    end_date    TIMESTAMP WITHOUT TIME ZONE,
    location    VARCHAR(255),
    CONSTRAINT pk_events PRIMARY KEY (id)
);

CREATE TABLE tickets
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ticket_number VARCHAR(255)                            NOT NULL,
    ticket_type   VARCHAR(255),
    price         DECIMAL,
    status        VARCHAR(255)                            NOT NULL,
    event_id      BIGINT                                  NOT NULL,
    CONSTRAINT pk_tickets PRIMARY KEY (id)
);

ALTER TABLE tickets
    ADD CONSTRAINT uc_tickets_ticket_number UNIQUE (ticket_number);

ALTER TABLE tickets
    ADD CONSTRAINT FK_TICKETS_ON_EVENT FOREIGN KEY (event_id) REFERENCES events (id);